//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by A Bot.rc
//
#define IDD_DIALOG1                     100
#define IDD_DIALOG2                     102
#define IDD_DIALOG3                     103
#define IDD_DIALOG5                     104
#define IDD_DIALOG6                     105
#define IDD_DIALOG7                     106
#define IDD_DIALOG8                     107
#define IDD_DIALOG4                     109
#define IDD_DIALOG9                     111
#define IDD_DVacs                       112
#define IDD_DSettings                   113
#define IDD_DKEYCONFIG                  115
#define IDR_RT_MANIFEST1                117
#define IDC_Cattack                     1000
#define IDC_BAutoAttack                 1000
#define IDC_Babout                      1001
#define IDC_BCcNow                      1001
#define IDC_Binstru                     1002
#define IDC_BInstructions               1002
#define IDC_BSettings                   1002
#define IDC_acounter                    1003
#define IDC_tmobcounter                 1005
#define IDC_RADIO1                      1005
#define IDC_PMob                        1005
#define IDC_BUnlimitedAttItemUA         1005
#define IDC_RChar1                      1005
#define IDC_BUnlimitedAttMoveUA         1006
#define IDC_RChar2                      1006
#define IDC_Rleft                       1007
#define IDC_RChar3                      1007
#define IDC_Rright                      1008
#define IDC_Schannel                    1008
#define IDC_PChannel                    1008
#define IDC_EDIT1                       1009
#define IDC_Euadelay                    1009
#define IDC_PServer                     1009
#define IDC_Smp                         1009
#define IDC_EItemFilterID               1009
#define IDC_EPlayerDetection_Allowed    1009
#define IDC_EuadelayA                   1010
#define IDC_PItem                       1010
#define IDC_EAutoCCSleep                1010
#define IDC_ELoginPassword              1010
#define IDC_EAutoCCAttack               1011
#define IDC_HpPer                       1011
#define IDC_PMouseY                     1012
#define IDC_ELoginPin                   1012
#define IDC_MpPer                       1012
#define IDC_PMap                        1013
#define IDC_ELoginChannel               1013
#define IDC_PHp                         1014
#define IDC_Shpval                      1015
#define IDC_PMp                         1015
#define IDC_Smpval                      1016
#define IDC_PHP2                        1016
#define IDC_PHp3                        1016
#define IDC_PExp                        1016
#define IDC_ExpPer                      1016
#define IDC_PMouseY2                    1017
#define IDC_RICHEDIT21                  1018
#define IDC_HpPer3                      1018
#define IDC_Cleft                       1023
#define IDC_BUnlimitedAtt               1023
#define IDC_Cright                      1024
#define IDC_BAutoCC                     1024
#define IDC_ScharX                      1025
#define IDC_BAutoPot                    1026
#define IDC_BAutoChat                   1027
#define IDC_BAuatoChat                  1027
#define IDC_ScharY                      1028
#define IDC_BAutoClick                  1029
#define IDC_BAutoLogin                  1030
#define IDC_BItemFilter                 1031
#define IDC_BLagHack                    1038
#define IDC_BAantVac                    1038
#define IDC_BDemVac                     1038
#define IDC_BInstantDrop                1039
#define IDC_BTubi                       1039
#define IDC_Sppl                        1046
#define IDC_STATICua                    1047
#define IDC_SIDC_SAcounter              1047
#define IDC_SAcounter                   1047
#define IDC_PAttack                     1047
#define IDC_BLoadList                   1053
#define IDC_BPplCounter                 1054
#define IDC_BSaveList                   1054
#define IDC_BSleepCounter               1055
#define IDC_BAddToList                  1055
#define IDC_SAutoLogin                  1056
#define IDC_BAttCounter                 1056
#define IDC_SItemFilter                 1057
#define IDC_BAutoSkill_1                1057
#define IDC_SAutoClick                  1058
#define IDC_BAutoSkill_2                1058
#define IDC_SAutoChat                   1059
#define IDC_SAutoCC                     1060
#define IDC_EAutoAttackSkill_1          1061
#define IDC_LIST1                       1063
#define IDC_SAutoAttack                 1064
#define IDC_SAutoPot                    1065
#define IDC_SUnlimitedAtt               1066
#define IDC_BHP                         1067
#define IDC_BMP                         1068
#define IDC_BAutoLoot                   1069
#define IDC_BAutoJump                   1070
#define IDC_BFixedMesos                 1072
#define IDC_BGodMode                    1072
#define IDC_EAutoAttackMob              1073
#define IDC_EAutoAttackDelay            1074
#define IDC_EAutoAttackSkill_2          1075
#define IDC_EAutoAttackLoot             1076
#define IDC_EAutoAttackJump             1077
#define IDC_PCharX                      1078
#define IDC_PCharY                      1079
#define IDC_PPl                         1080
#define IDC_EAutoPotHP                  1081
#define IDC_EAutoPotMP                  1082
#define IDC_EAutoChatTEXT               1083
#define IDC_EAutoChatDelay              1084
#define IDC_EAutoChatTEXT_2             1085
#define IDC_EAutoClickDelay             1086
#define IDC_EAutoCCPeople               1087
#define IDC_BUnlimitedAtt_Attacks       1088
#define IDC_BUnlimitedAtt_Delay         1089
#define IDC_EUnlimitedAtt_Attacks       1090
#define IDC_EUnlimitedAtt_Delay         1091
#define IDC_SUnlimitedAtt_Pos_1         1092
#define IDC_SUnlimitedAtt_Pos_2         1093
#define IDC_CWorldSelect                1095
#define IDC_BVacs                       1096
#define IDC_CCharSelect                 1096
#define IDC_ELoginId                    1097
#define IDC_BUTTON1                     1098
#define IDC_BSettingsBrowse             1098
#define IDC_CHECK1                      1099
#define IDC_CPlayerDetection            1099
#define IDC_CHECK2                      1100
#define IDC_CAutoSaveSettings           1100
#define IDC_CHECK3                      1101
#define IDC_CAutoLoadSettings           1101
#define IDC_EDIT3                       1102
#define IDC_ESettingsDir                1102
#define IDC_COMBO1                      1103
#define IDC_CAutoAttack_Off             1103
#define IDC_PHpBar                      1104
#define IDC_CAutoPot_Off                1104
#define IDC_CUnlimitedAttack_Off        1105
#define IDC_SVacRange                   1106
#define IDC_CAutoCC_Off                 1106
#define IDC_PMpBar                      1107
#define IDC_EVacRangeValue              1107
#define IDC_CAutoChat_Off               1107
#define IDC_PROGRESS3                   1108
#define IDC_PExpBar                     1108
#define IDC_CAutoClick_Off              1108
#define IDC_CStatBar                    1109
#define IDC_CItemFilter_OFF             1109
#define IDC_CPauseResumeHacksAutoLogin  1110
#define IDC_CAutoLogin_OFF              1110
#define IDC_CLaunchWhenDCAutoLogin      1111
#define IDC_COMBO2                      1111
#define IDC_CLoot_Key                   1111
#define IDC_EMapleDirAutoLogin          1112
#define IDC_CTubi_OFF                   1112
#define IDC_COMBO3                      1112
#define IDC_CJump_Key                   1112
#define IDC_BBrowseToMapleAutoLogin     1113
#define IDC_CVAC_OFF                    1113
#define IDC_COMBO4                      1113
#define IDC_CSkill_1_Key                1113
#define IDC_BUTTON2                     1114
#define IDC_BKEYCONFIG                  1114
#define IDC_COMBO5                      1114
#define IDC_CSkill_2_Key                1114
#define IDC_CGodMode_OFF                1115
#define IDC_COMBO6                      1115
#define IDC_CHp_Key                     1115
#define IDC_DisableHotkeys              1116
#define IDC_COMBO7                      1116
#define IDC_CMp_Key                     1116
#define IDC_CAttack_Key                 1117
#define LEFT	0x25
#define RIGHT	0x27

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        118
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1118
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
